version: '3.8'

services:
  backend:
    build:
      context: C:/Users/sk.hasna/Desktop/Employee-Management/employee-management-backend  # Full path to the backend folder where Dockerfile exists
    ports:
      - "5000:5000"  # Expose port 5000 for the backend service
    env_file:
      - C:/Users/sk.hasna/Desktop/Employee-Management/employee-management-backend/.env  # Full path to the .env file
    depends_on:
      - db  # Ensure that the backend starts after the MySQL container is up
    networks:
      - app-network  # Network connection to the db service
    restart: always  # Ensure that the backend container restarts if it stops unexpectedly

  db:
    image: mysql:8.0  # Use the official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: Hasnahasna  # Root password for MySQL
      MYSQL_DATABASE: employee_management  # The database to be created
    ports:
      - "3306:3306"  # Expose MySQL's default port 3306
    networks:
      - app-network  # Network connection to the backend service
    volumes:
      - db_data:/var/lib/mysql  # Persist data between container restarts
    restart: always  # Ensure that the db container restarts if it stops unexpectedly

networks:
  app-network:
    driver: bridge  

volumes:
  db_data:
    driver: local  
